source "http://rubygems.org"

gem 'bundler', '>= 1.0.10'
gem 'rake'
gem 'nats', '0.4.24', :require => 'nats/client'
gem 'eventmachine', '0.12.11.cloudfoundry.3'

gem "http_parser.rb", :require => "http/parser"
gem "yajl-ruby", :require => ["yajl", "yajl/json_gem"]

gem 'vcap_common', '~> 1.0.3'
gem 'vcap_logging', :require => ['vcap/logging']

group :test do
  gem "rspec"
  gem "rcov", '0.9.11'
  gem "ci_reporter"
end
