source :rubygems

gem 'eventmachine'
gem 'nats', '~> 0.4.26'
gem 'logging', '= 1.5.2'
gem 'yajl-ruby', '~> 0.8.3'

gem 'vcap_common', path: '../common'
gem 'vcap_logging', '>= 0.1.3'
gem 'vcap_staging', path: '../staging'

group :test do
  gem 'rspec'
  gem 'sinatra'
  gem 'webmock'
end
