source :rubygems

gem 'eventmachine'
gem 'nats', '~> 0.4.24'
gem 'rake'
gem 'logging', '= 1.5.2'
gem 'yajl-ruby', '~> 0.8.3'

gem 'vcap_common', '1.0.3'
gem 'vcap_logging', '>= 0.1.3'
gem 'vcap_staging', '~> 0.1.32'

group :test do
  gem 'rspec'
  gem 'sinatra'
  gem 'webmock'
end
