maintainer       "VMware"
maintainer_email "support@vmware.com"
license          "Apache 2.0"
description      "Installs/Configures nginx branch 4.0.0"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "4.0.0"
depends "ruby"
depends "cloudfoundry"
depends "deployment"
depends "nginx"
