default[:postgresql][:server_root_password] = "changeme"
default[:postgresql][:server_root_user] = "cloudfoundry"
default[:postgresql][:database] = "pg_service"
default[:postgresql][:index] = "0"
default[:postgresql][:max_db_size] = "500"
default[:postgresql][:available_storage] = "1024"
default[:postgresql][:token] = "changepostgresqltoken"
