maintainer       "VMware"
maintainer_email "support@vmware.com"
license          "Apache 2.0"
description      "Installs/Configures MongoDB"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.markdown'))
version          "0.3.10"
depends "ruby"
depends "cloudfoundry"
depends "deployment"
depends "cloud_controller"
