source "http://rubygems.org"

gem 'nats', '0.4.24', :require => 'nats/client'
gem 'eventmachine', '0.12.11.cloudfoundry.3'

gem 'vcap_common', '1.0.3'
gem 'vcap_logging', :require => ['vcap/logging']

gemspec
